#!/bin/bash

sudo apt-get update
wget https://github.com/mysteriumnetwork/node/releases/latest/download/myst_linux_amd64.deb
sudo DEBIAN_FRONTEND=noninteractive dpkg -i --force-depends myst_linux_amd64.deb && sudo apt-get -y --fix-broken install
rm myst_linux_amd64.deb
sudo chmod 0755 /etc/mysterium-node/config-mainnet.toml
sudo grep -q Group= /lib/systemd/system/mysterium-node.service && ed -s /lib/systemd/system/mysterium-node.service  <<< $'/Group=/\na\nNice=-20\n.\nw\nq' > /dev/null
sudo grep -q EnvironmentFile /lib/systemd/system/mysterium-node.service && ed -s /lib/systemd/system/mysterium-node.service  <<< $'/EnvironmentFile/\na\nExecStartPre=/etc/script/myst-config\n.\nw\nq' > /dev/null
sed -i '/service/ s//--auto-reconnect service set value true/g' /lib/systemd/system/mysterium-node.service && sudo systemctl daemon-reload && sudo systemctl enable mysterium-node.service
sudo reboot
